<?xml version="1.0" ?>
<testsuite name="TestAServices.UserTestCase-20240411103102" tests="5" time="0.075" failures="0" errors="1">
	<testcase classname="TestAServices.UserTestCase" name="test_login_user" time="0.037"/>
	<testcase classname="TestAServices.UserTestCase" name="test_login_user_fail" time="0.001"/>
	<testcase classname="TestAServices.UserTestCase" name="test_register_user" time="0.011"/>
	<testcase classname="TestAServices.UserTestCase" name="test_saving" time="0.003"/>
	<testcase classname="TestAServices.UserTestCase" name="test_prediction" time="0.024">
		<error type="KeyError" message="'message'"><![CDATA[Traceback (most recent call last):
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\backend\tests\TestAServices.py", line 72, in test_prediction
    self.assertEqual(response['message'], 'Your predicted class is: 3D animation and visualization')
                     ~~~~~~~~^^^^^^^^^^^
KeyError: 'message'
]]></error>
	</testcase>
	<system-out><![CDATA[]]></system-out>
	<system-err><![CDATA[]]></system-err>
</testsuite>
