<?xml version="1.0" ?>
<testsuite name="TestRoutes.TestUsersBlueprint-20240411094203" tests="5" time="0.054" failures="0" errors="1">
	<testcase classname="TestRoutes.TestUsersBlueprint" name="test_login" time="0.020"/>
	<testcase classname="TestRoutes.TestUsersBlueprint" name="test_login_fail" time="0.002"/>
	<testcase classname="TestRoutes.TestUsersBlueprint" name="test_prediction" time="0.002"/>
	<testcase classname="TestRoutes.TestUsersBlueprint" name="test_save" time="0.002"/>
	<testcase classname="TestRoutes.TestUsersBlueprint" name="test_register" time="0.028">
		<error type="AssertionError" message="{'message': 'User registered successfully', 'userID': 7} != {'message': 'User registered successfully', 'userID': 3}
- {'message': 'User registered successfully', 'userID': 7}
?                                                       ^

+ {'message': 'User registered successfully', 'userID': 3}
?                                                       ^
"><![CDATA[Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\unittest\mock.py", line 1378, in patched
    return func(*newargs, **newkeywargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\backend\tests\TestRoutes.py", line 24, in test_register
    self.assertEqual(data, {'message': 'User registered successfully', 'userID': 3})
AssertionError: {'message': 'User registered successfully', 'userID': 7} != {'message': 'User registered successfully', 'userID': 3}
- {'message': 'User registered successfully', 'userID': 7}
?                                                       ^

+ {'message': 'User registered successfully', 'userID': 3}
?                                                       ^

]]></error>
	</testcase>
	<system-out><![CDATA[]]></system-out>
	<system-err><![CDATA[]]></system-err>
</testsuite>
