<?xml version="1.0" ?>
<testsuite name="TestRoutes.TestUsersBlueprint-20240411094128" tests="5" time="0.068" failures="0" errors="1">
	<testcase classname="TestRoutes.TestUsersBlueprint" name="test_login" time="0.023"/>
	<testcase classname="TestRoutes.TestUsersBlueprint" name="test_login_fail" time="0.002"/>
	<testcase classname="TestRoutes.TestUsersBlueprint" name="test_prediction" time="0.003"/>
	<testcase classname="TestRoutes.TestUsersBlueprint" name="test_save" time="0.002"/>
	<testcase classname="TestRoutes.TestUsersBlueprint" name="test_register" time="0.039">
		<error type="AssertionError" message="{'message': 'User registered successfully', 'userID': 6} != {'message': 'User registered successfully', 'userID': &lt;class 'int'&gt;}
- {'message': 'User registered successfully', 'userID': 6}
?                                                       ^

+ {'message': 'User registered successfully', 'userID': &lt;class 'int'&gt;}
?                                                       ^^^^^^^^^^^^^
"><![CDATA[Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\unittest\mock.py", line 1378, in patched
    return func(*newargs, **newkeywargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\backend\tests\TestRoutes.py", line 24, in test_register
    self.assertEqual(data, {'message': 'User registered successfully', 'userID': int})
AssertionError: {'message': 'User registered successfully', 'userID': 6} != {'message': 'User registered successfully', 'userID': <class 'int'>}
- {'message': 'User registered successfully', 'userID': 6}
?                                                       ^

+ {'message': 'User registered successfully', 'userID': <class 'int'>}
?                                                       ^^^^^^^^^^^^^

]]></error>
	</testcase>
	<system-out><![CDATA[]]></system-out>
	<system-err><![CDATA[]]></system-err>
</testsuite>
