<?xml version="1.0" ?>
<testsuite name="TestModelPrediction.TestModelPredictions-20240504142445" tests="1" time="0.005" failures="0" errors="0">
	<testcase classname="TestModelPrediction.TestModelPredictions" name="test_prediction_shape" time="0.005"/>
	<system-out><![CDATA[]]></system-out>
	<system-err><![CDATA[[2024-05-04 14:24:45,791] ERROR in app: Exception on /register [POST]
Traceback (most recent call last):
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\backend\routes.py", line 9, in register
    new_user = register_user(user_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\backend\services.py", line 39, in register_user
    db.session.commit()
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\orm\scoping.py", line 597, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4296, in flush
    self._flush(objects)
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4431, in _flush
    with util.safe_reraise():
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4392, in _flush
    flush_context.execute()
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 60, in save_obj
    for (
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 223, in _organize_states_for_save
    for state, dict_, mapper, connection in _connections_for_states(
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1753, in _connections_for_states
    connection = uowtransaction.transaction.connection(base_mapper)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in connection
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 994, in connection
    return self._connection_for_bind(bind, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1130, in _connection_for_bind
    conn = self._parent._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1144, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3280, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3304, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 617, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\.venv\Lib\site-packages\MySQLdb\connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
TypeError: 'ssl-mode' is an invalid keyword argument for connect()
]]></system-err>
</testsuite>
