<?xml version="1.0" ?>
<testsuite name="TestRoutes.TestUsersBlueprint-20240411092346" tests="5" time="0.072" failures="0" errors="1">
	<testcase classname="TestRoutes.TestUsersBlueprint" name="test_login" time="0.021"/>
	<testcase classname="TestRoutes.TestUsersBlueprint" name="test_login_fail" time="0.003"/>
	<testcase classname="TestRoutes.TestUsersBlueprint" name="test_prediction" time="0.004"/>
	<testcase classname="TestRoutes.TestUsersBlueprint" name="test_save" time="0.002"/>
	<testcase classname="TestRoutes.TestUsersBlueprint" name="test_register" time="0.042">
		<error type="TypeError" message="unhashable type: 'dict'"><![CDATA[Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\unittest\mock.py", line 1378, in patched
    return func(*newargs, **newkeywargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Omistaja\PycharmProjects\MLEngine3\backend\tests\TestRoutes.py", line 22, in test_register
    self.assertEqual(data, {{'message': 'User registered successfully', 'userID': 1}})
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'dict'
]]></error>
	</testcase>
	<system-out><![CDATA[]]></system-out>
	<system-err><![CDATA[]]></system-err>
</testsuite>
